### ISSUE TITLE
tflite Model

### ISSUE THREAD

**Issue by AbdulFMS** [xadrianzetx/mobileunet-tensorflow#15]
Can you provide the pre-trained model please! @xadrianzetx

**Comment by xadrianzetx** [comment]
You can find quantized `.tflite` model [here](https://github.com/xadrianzetx/lanefinder/tree/master/assets/models). [Zero point and scale](https://www.tensorflow.org/lite/performance/post_training_quantization#representation_for_quantized_tensors) values for this model are available [here](https://github.com/xadrianzetx/lanefinder/blob/master/config.yaml).

**Comment by AbdulFMS** [comment]
Thank you!
